[[plugins]]
repo = 'nvim-telescope/telescope-z.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope-ghq.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope-frecency.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope-project.nvim'

[[plugins]]
repo = 'LinArcX/telescope-command-palette.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
lua_add = '''
require('telescope_config')
'''
