[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'wadackel/vim-dogrun'

[[plugins]]
repo = 'sainnhe/everforest'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'ishan9299/nvim-solarized-lua'
