[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = "release"
hook_add = '''
    source ~/.config/nvim/plugins/coc.vim
'''

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'qpkorr/vim-renamer'

[[plugins]]
repo = 'voldikss/vim-translator'
hook_add = '''
    source ~/.config/nvim/plugins/translator.vim
'''

[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = '''
    source ~/.config/nvim/plugins/startify.vim
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
do = 'TSUpdate'
hook_add = '''
    lua require('treesitter')
'''

[[plugins]]
repo = 'ryotai25/memolist.vim'
hook_add = '''
    source ~/.config/nvim/plugins/memolist.vim
'''

[[plugins]]
repo = 'junegunn/goyo.vim'

[[plugins]]
repo = 'mattn/vim-findroot'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'hasundue/vim-pluto'

[[plugins]]
repo = 'hkupty/iron.nvim'
hook_add = '''
    lua require('iron')
'''

[[plugins]]
repo = 'akinsho/toggleterm.nvim'
hook_add = '''
    lua require('toggle_term')
'''

[[plugins]]
repo = 'kdheepak/lazygit.nvim'
hook_add = '''
    source ~/.config/nvim/plugins/lazygit.vim
'''

[[plugins]]
repo = 'TimUntersberger/neogit'
hook_add = '''
    lua require('neogit').setup{}
'''

[[plugins]]
repo = 'nvim-lua/popup.nvim'

# [[plugins]]
# repo = 'SirVer/ultisnips'

[[plugins]]
 repo = 'ryotai25/vim-snippets'

[[plugins]]
 repo = 'folke/todo-comments.nvim'
hook_add = '''
    lua require('todo-comments').setup{}
'''

[[plugins]]
repo = 'akinsho/bufferline.nvim'
hook_add = '''
    lua require('bufferl')
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = '''
    lua require('lualine').setup{ options = { component_separators = '|' , section_separators = { left = '', right = ''} } }
'''

[[plugins]]
repo = 'Pocco81/true-zen.nvim'
hook_add = '''
    lua require("true-zen").setup{}
'''

[[plugins]]
repo = 'kkharji/sqlite.lua'

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
hook_add = '''
    lua require("nvim-tree").setup{}
'''

[[plugins]]
repo = 'theblob42/drex.nvim'

[[plugins]]
repo = 'glepnir/dashboard-nvim'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hook_add = '''
    lua require('gitsigns').setup()
'''
