[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex', 'latex']
hook_add = '''
source ~/.config/nvim/plugins/latex.vim
'''

[[plugins]]
repo = 'skanehira/preview-markdown.vim'
on_ft = 'md'
hook_add = '''
let g:preview_markdown_parser='glow'
'''

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'
on_ft = ['julia', 'tex', 'latex']
hook_add = '''
let g:latex_to_unicode_file_types = ['julia', 'tex', 'latex']
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'hasundue/vim-pluto'
on_ft = 'julia'

[[plugins]]
repo = 'jalvesaq/Nvim-R'
on_ft = 'r'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]]
repo = 'stevearc/vim-arduino'
on_ft = 'ino'

[[plugins]]
repo = 'vim-pandoc/vim-pandoc-syntax'
on_ft = 'quarto'

[[plugins]]
repo = 'quarto-dev/quarto-vim'
on_ft = 'quarto'

[[plugins]]
repo = 'kevinhwang91/nvim-bqf'
on_ft = 'qf'
