[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = "release"
hook_add = '''
    source ~/.config/nvim/plugins/coc.vim
'''

[[plugins]]
repo = 'voldikss/vim-translator'
hook_add = '''
    source ~/.config/nvim/plugins/translator.vim
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
do = 'TSUpdate'
hook_add = '''
    lua require('treesitter')
'''
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'

[[plugins]]
repo = 'ryotai25/memolist.vim'
hook_add = '''
    source ~/.config/nvim/plugins/memolist.vim
'''

[[plugins]]
repo = 'mattn/vim-findroot'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'hkupty/iron.nvim'
hook_add = '''
    lua require('iron')
    nnoremap <silent> <leader>r <cmd>IronFocus<CR>
'''

[[plugins]]
repo = 'akinsho/toggleterm.nvim'
hook_add = '''
    lua require('toggle_term')
'''

[[plugins]]
repo = 'kdheepak/lazygit.nvim'
hook_add = '''
    source ~/.config/nvim/plugins/lazygit.vim
'''

# 依存先
[[plugins]]
repo = 'nvim-lua/popup.nvim'

# [[plugins]]
# repo = 'SirVer/ultisnips'

[[plugins]]
 repo = 'ryotai25/vim-snippets'

[[plugins]]
 repo = 'folke/todo-comments.nvim'
hook_add = "lua require('todo-comments').setup()"

[[plugins]]
repo = 'akinsho/bufferline.nvim'
hook_add = '''
lua require('bufferl')
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = '''
    lua require('lualine').setup{ options = { component_separators = '|' , section_separators = { left = '', right = ''} } }
'''

[[plugins]]
repo = 'Pocco81/true-zen.nvim'
hook_add = "lua require('true-zen').setup()"

[[plugins]]
repo = 'kkharji/sqlite.lua'

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
hook_add = '''
lua require('nvim-tree').setup{}
'''

[[plugins]]
repo = 'theblob42/drex.nvim'

[[plugins]]
repo = 'glepnir/dashboard-nvim'
hook_add = '''
    lua require('startup')
'''

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hook_add = "lua require('gitsigns').setup()"

[[plugins]]
repo = 'chentoast/marks.nvim'
hook_add = "lua require('marks').setup()"

[[plugins]]
repo = 'unblevable/quick-scope'

[[plugins]]
repo = 'kylechui/nvim-surround'
hook_add = '''
lua require('nvim-surround').setup()
'''

[[plugins]]
repo = 'numToStr/Comment.nvim'
hook_add = "lua require('Comment').setup()"
