[[plugins]]
repo = 'voldikss/vim-translator'
hook_add = '''
let g:translator_target_lang = 'ja'
let g:vtm_default_engines = ['google']
nnoremap <silent> <Leader>w <Plug>TranslateW
vnoremap <silent> <Leader>w <Plug>TranslateWV
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
do = 'TSUpdate'
lua_add = '''
require('nvim-treesitter_config')
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'

[[plugins]]
repo = 'ryotai25/memolist.vim'
hook_add = '''
source ~/.config/nvim/plugins/memolist.vim
'''

[[plugins]]
repo = 'mattn/vim-findroot'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
lua_add = '''
require'nvim-web-devicons'.setup {default = true}
'''

[[plugins]]
repo = 'hkupty/iron.nvim'
hook_add = '''
lua require('iron')
nnoremap <silent> <leader>r <cmd>IronFocus<CR>
'''

[[plugins]]
repo = 'akinsho/toggleterm.nvim'
lua_add = '''
require('toggleterm')
'''

[[plugins]]
repo = 'kdheepak/lazygit.nvim'
hook_add = '''
source ~/.config/nvim/plugins/lazygit.vim
'''

# 依存先
[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
 repo = 'folke/todo-comments.nvim'
lua_add = '''
require('todo-comments').setup()
'''

[[plugins]]
repo = 'akinsho/bufferline.nvim'
lua_add = '''
require('bufferline_config')
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
lua_add = '''
require('lualine').setup{ 
    options = { 
        component_separators = '|' , 
        section_separators = { left = '', right = ''} ,
    },
}
'''
    # sections = {
    #     lualine_x = { "require('lsp-status').status()", "encoding", "fileformat", "filetype" }
    # },

[[plugins]]
repo = 'kkharji/sqlite.lua'

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
lua_add = '''
require('nvim-tree').setup()
'''

[[plugins]]
repo = 'theblob42/drex.nvim'

# [[plugins]]
# repo = 'glepnir/dashboard-nvim'
# lua_add = '''
# require('dashboard_config')
# '''

[[plugins]]
repo = 'goolord/alpha-nvim'
lua_add = '''
require('alpha').setup(require'alpha.themes.startify'.config)
'''

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
lua_add = '''
require('gitsigns').setup()
'''

[[plugins]]
repo = 'unblevable/quick-scope'

[[plugins]]
repo = 'kylechui/nvim-surround'
lua_add = '''
require('nvim-surround').setup()
'''

[[plugins]]
repo = 'numToStr/Comment.nvim'
lua_add = '''
require('Comment').setup()
'''

[[plugins]]
repo = 'levouh/tint.nvim'
lua_add = '''
require('tint').setup()
'''

# [[plugins]]
# repo = 'epwalsh/obsidian.nvim'
# lua_add = '''
# require("obsidian").setup({
#   dir = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Notes",
#   daily_notes = {
#     folder = "Daily Notes",
#   },
#   completion = {
#     nvim_cmp = true, -- if using nvim-cmp, otherwise set to false
#   }
# })
# '''

[[plugins]]
repo = 'brglng/vim-im-select'
hook_add = '''
let g:im_select_default = 'com.apple.inputmethod.Kotoeri.RomajiTyping.Roman'
'''
